# should run "cargo build --verbose" and "cargo test --verbose" by default
# reference: https://docs.travis-ci.com/user/languages/rust/
language: rust
os:
    - debian
    - osx

env:
    - PATH=$TRAVIS_BUILD_DIR/target/debug:$TRAVIS_BUILD_DIR/tests/bats:$PATH

script:
    - cargo build --verbose --all
    - cargo test --verbose --all
    - ./tests/test-binary.bats
